# Stubs for pybag.base.util.interval (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class PyDisjointIntervals(pybind11_object):
    def __init__(self, intv_list: Optional[List[Tuple[int, int]]]=None, val_list: Optional[List[Any]]=None): ...
