# Stubs for pybag.base.util.interval (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class PyDisjointIntervals(pybind11_object):
    def __init__(self, *args, **kwargs): ...
